### ISSUE TITLE
error patching

### ISSUE THREAD

**Issue by victorsanva** [5cr1pt/GitCracken#27]
I have this error patching. 
any solution?
/home/v2c/GitCracken/GitCracken/dist/src/appId.js:23
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/v2c/GitCracken/GitCracken/dist/src/index.js:6:10)

**Comment by jampack** [comment]
for linux try this https://github.com/5cr1pt/GitCracken/issues/29#issuecomment-597836289
