### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by GitSarp** [5cr1pt/GitCracken#30]
(node:30012) UnhandledPromiseRejectionWarning: Error: Can't find app.asar!
    at new Patcher (E:\code\GitCracken\GitCracken\dist\src\patcher.js:55:19)
    at executeActions (E:\code\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:9:21)
    at Command.<anonymous> (E:\code\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:87:11)
    at Command.listener (E:\code\GitCracken\GitCracken\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:311:20)
    at Command.parseArgs (E:\code\GitCracken\GitCracken\node_modules\commander\index.js:665:12)
    at Command.parse (E:\code\GitCracken\GitCracken\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (E:\code\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:30012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin
g inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (se
e https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:30012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reje
ctions that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by 5cr1pt** [comment]
With **GitKraken 6.5.4**, **node v12.16.1** and **yarn 1.22.4**, That's my way and it works well:
first, download both node.js and yarn with `.msi` installer and install with default options.
then
```bash
C:\Users\Anonymous\Desktop
λ node --version
v12.16.1

C:\Users\Anonymous\Desktop
λ yarn -version
1.22.4

C:\Users\Anonymous\Desktop
λ git clone https://github.com/5cr1pt/GitCracken.git
Cloning into 'GitCracken'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (63/63), done.
Receiving objects:  71% (96/135)   d 73 (delta 19), pack-reused 52
Receiving objects: 100% (135/135), 98.64 KiB | 863.00 KiB/s, done.
Resolving deltas: 100% (49/49), done.

C:\Users\Anonymous\Desktop
λ cd GitCracken\GitCracken\

C:\Users\Anonymous\Desktop\GitCracken\GitCracken (master -> origin)
λ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

Done in 21.35s.

C:\Users\Anonymous\Desktop\GitCracken\GitCracken (master -> origin)
λ yarn build
yarn run v1.22.4
$ rimraf dist && tsc
Done in 4.38s.

C:\Users\Anonymous\Desktop\GitCracken\GitCracken (master -> origin)
λ node dist\bin\gitcracken.js patcher

 ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
 ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝

• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

==> � Backup C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar ➔ C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar.1585190760686.backup
==> � Unpack C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar ➔ C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app
==> � Patch C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app with pro features
==> � Pack C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app ➔ C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar
==> � Remove C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app
==> � Patching done!
```

**Comment by jackey-jiang** [comment]
MacOS. Same question. Not Work

**Comment by 5cr1pt** [comment]
> MacOS. Same question. Not Work

check your env and versions

**Comment by astrot1988** [comment]
Just try with administrative priveleges.

> MacOS. Same question. Not Work

**Comment by hsiwei0620** [comment]
Hi @5cr1pt , When I execute `node dist\bin\gitcracken.js patcher`, the Gitkraken app can not open again. My operation steps are exactly the same as yours and have been successfully executed.
Do you have any idea ?

GitKraken 6.5.0
node version : v12.16.1
yarn -version: 1.22.4

**Comment by MrChe** [comment]
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module '/Users/macbookpro15/Projects/GitCracken/GitCracken/distbingitcracken.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by MrChe** [comment]
```(node:81892) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/Users/macbookpro15/Downloads/gitkraken/resources/app.asar'
    at Object.statSync (fs.js:947:3)
    at Object.statSync (/Users/macbookpro15/Projects/GitCracken/GitCracken/node_modules/graceful-fs/polyfills.js:301:34)
    at getStatsSync (/Users/macbookpro15/Projects/GitCracken/GitCracken/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/Users/macbookpro15/Projects/GitCracken/GitCracken/node_modules/fs-extra/lib/util/stat.js:90:33)
    at Object.copySync (/Users/macbookpro15/Projects/GitCracken/GitCracken/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at Patcher.backupAsar (/Users/macbookpro15/Projects/GitCracken/GitCracken/dist/src/patcher.js:75:12)
    at executeActions (/Users/macbookpro15/Projects/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:18:95)
    at Command.<anonymous> (/Users/macbookpro15/Projects/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/Users/macbookpro15/Projects/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:305:20)
    at Command.parseArgs (/Users/macbookpro15/Projects/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/Users/macbookpro15/Projects/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/macbookpro15/Projects/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
(node:81892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:81892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by creazy231** [comment]
Just did everything mentioned in the README and it works perfectly on my Hackintosh ❤️

![image](https://user-images.githubusercontent.com/13473174/78807004-c17d0100-79c3-11ea-93c3-cf036b415137.png)

Setup:
using nvm
```
$ node -v
v12.16.1
```
```
$ yarn -v
1.22.4
```

**Comment by OmegaClone** [comment]
Work perfectly. You don't need yarn however, just run `npm install` and `npm run build`

**Comment by MrChe** [comment]
I try it with npm, buts it's not helped me

**Comment by GitSarp** [comment]
> With **GitKraken 6.5.4**, **node v12.16.1** and **yarn 1.22.4**, That's my way and it works well:
> first, download both node.js and yarn with `.msi` installer and install with default options.
> then
> 
> ```shell
> C:\Users\Anonymous\Desktop
> λ node --version
> v12.16.1
> 
> C:\Users\Anonymous\Desktop
> λ yarn -version
> 1.22.4
> 
> C:\Users\Anonymous\Desktop
> λ git clone https://github.com/5cr1pt/GitCracken.git
> Cloning into 'GitCracken'...
> remote: Enumerating objects: 83, done.
> remote: Counting objects: 100% (83/83), done.
> remote: Compressing objects: 100% (63/63), done.
> Receiving objects:  71% (96/135)   d 73 (delta 19), pack-reused 52
> Receiving objects: 100% (135/135), 98.64 KiB | 863.00 KiB/s, done.
> Resolving deltas: 100% (49/49), done.
> 
> C:\Users\Anonymous\Desktop
> λ cd GitCracken\GitCracken\
> 
> C:\Users\Anonymous\Desktop\GitCracken\GitCracken (master -> origin)
> λ yarn install
> yarn install v1.22.4
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> 
> Done in 21.35s.
> 
> C:\Users\Anonymous\Desktop\GitCracken\GitCracken (master -> origin)
> λ yarn build
> yarn run v1.22.4
> $ rimraf dist && tsc
> Done in 4.38s.
> 
> C:\Users\Anonymous\Desktop\GitCracken\GitCracken (master -> origin)
> λ node dist\bin\gitcracken.js patcher
> 
>  ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
> ██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
> ██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
> ██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
> ╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
>  ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
> 
> • Description: GitKraken utils for non-commercial use
> • Version: 0.6.2
> • Author: KillWolfVlad
> • License: MIT
> • Home Page: https://pastebin.com/u/KillWolfVlad
> 
> ==> � Backup C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar ➔ C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar.1585190760686.backup
> ==> � Unpack C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar ➔ C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app
> ==> � Patch C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app with pro features
> ==> � Pack C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app ➔ C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar
> ==> � Remove C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app
> ==> � Patching done!
> ```

It helps me,thanks

**Comment by djmemo** [comment]
> 
> 
> > With **GitKraken 6.5.4**, **node v12.16.1** and **yarn 1.22.4**, That's my way and it works well:
> > first, download both node.js and yarn with `.msi` installer and install with default options.
> > then
> > ```shell
> > C:\Users\Anonymous\Desktop
> > λ node --version
> > v12.16.1
> > 
> > C:\Users\Anonymous\Desktop
> > λ yarn -version
> > 1.22.4
> > 
> > C:\Users\Anonymous\Desktop
> > λ git clone https://github.com/5cr1pt/GitCracken.git
> > Cloning into 'GitCracken'...
> > remote: Enumerating objects: 83, done.
> > remote: Counting objects: 100% (83/83), done.
> > remote: Compressing objects: 100% (63/63), done.
> > Receiving objects:  71% (96/135)   d 73 (delta 19), pack-reused 52
> > Receiving objects: 100% (135/135), 98.64 KiB | 863.00 KiB/s, done.
> > Resolving deltas: 100% (49/49), done.
> > 
> > C:\Users\Anonymous\Desktop
> > λ cd GitCracken\GitCracken\
> > 
> > C:\Users\Anonymous\Desktop\GitCracken\GitCracken (master -> origin)
> > λ yarn install
> > yarn install v1.22.4
> > [1/4] Resolving packages...
> > [2/4] Fetching packages...
> > [3/4] Linking dependencies...
> > [4/4] Building fresh packages...
> > 
> > Done in 21.35s.
> > 
> > C:\Users\Anonymous\Desktop\GitCracken\GitCracken (master -> origin)
> > λ yarn build
> > yarn run v1.22.4
> > $ rimraf dist && tsc
> > Done in 4.38s.
> > 
> > C:\Users\Anonymous\Desktop\GitCracken\GitCracken (master -> origin)
> > λ node dist\bin\gitcracken.js patcher
> > 
> >  ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
> > ██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
> > ██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
> > ██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
> > ╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
> >  ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
> > 
> > • Description: GitKraken utils for non-commercial use
> > • Version: 0.6.2
> > • Author: KillWolfVlad
> > • License: MIT
> > • Home Page: https://pastebin.com/u/KillWolfVlad
> > 
> > ==> � Backup C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar ➔ C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar.1585190760686.backup
> > ==> � Unpack C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar ➔ C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app
> > ==> � Patch C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app with pro features
> > ==> � Pack C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app ➔ C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app.asar
> > ==> � Remove C:\Users\Anonymous\AppData\Local\gitkraken\app-6.5.4\resources\app
> > ==> � Patching done!
> > ```
> 
> It helps me,thanks

How did you install Gitkraken? in Stand-Alone version ?

**Comment by aghayeff** [comment]
Same issue in Ubuntu
