### ISSUE TITLE
Error on debian

### ISSUE THREAD

**Issue by jlopezjuy** [5cr1pt/GitCracken#31]
I'm trying to run sudo node dist/bin/gitcracken.js patcher  BUT....
/home/juan/Proyectos/GitCracken-master/GitCracken/dist/src/appId.js:23
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/juan/Proyectos/GitCracken-master/GitCracken/dist/src/index.js:6:10)

**Comment by smartdperez** [comment]
fix in 
/home/juan/Proyectos/GitCracken-master/GitCracken/dist/src/appId.js:23

        catch{
            mac = uuid.v4();
        }


for 

        catch (mac) {
            mac = uuid.v4();
        }

works for me...

**Comment by jlopezjuy** [comment]
great!!! works !!

**Comment by djmemo** [comment]
Merge this #18 @5cr1pt
