### ISSUE TITLE
Not work on ubuntu 18.04 .Could you help me?

### ISSUE THREAD

**Issue by Bit-urd** [5cr1pt/GitCracken#34]
There is no response when opening, staying on the loading page, and the main page does not appear.

**Comment by Bit-urd** [comment]
![image](https://user-images.githubusercontent.com/43745133/80222696-ce634b00-8679-11ea-90d8-8f5819c30b4c.png)
Keep on this page.

**Comment by ACBingo** [comment]
same issue with me

**Comment by souhaiebtar** [comment]
i tried on ubuntu 20.04, with a fresh install of the 6.6 (the last version to date) and it works, it should also work on 18.04, try

start clean
```
sudo apt-get autoremove gitcraken
sudo rm -rf /usr/share/gitcraken
sudo dpkg -i gitcraken-amd64.deb
```
than

```
git clone https://github.com/5cr1pt/GitCracken
cd GitCracken/GitCracken/
yarn install
yarn build
sudo node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"   
```
if you are using `nvm` or  any node version manager, put the entire path to node for me it was

```
 sudo /home/MY_USER_NAME/.nvm/versions/node/v10.18.0/bin/node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"  
```

**Comment by rj-hwang** [comment]
My try: work on Ubuntu-20.04 with Gitkraken-7.0.0 not 6.5.0

**Comment by engelcss** [comment]
` sudo /home/MY_USER_NAME/.nvm/versions/node/v10.18.0/bin/node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"`

this work for me - Ubuntu 20.04 with GitKraken-7.0.0 and nvm, thanks souhaiebtar

**Comment by damianlluch** [comment]
Hi

I have this result:

(node:19315) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/usr/share/gitkraken/resources/app.asar'


any suggestions?

**Comment by engelcss** [comment]
Hi, check this file 
`/usr/share/gitkraken/resources/app.asar`
Is this exists?

I think you install gitkraken via snap, but this script do not work with it.

> Working on GNU/Linux (without snap), Windows and macOS.

**Comment by damianlluch** [comment]
Hi,

Yes I installed GitKraken with Snap.

How I install Gitkraken for work ok?

**Comment by engelcss** [comment]
Okay, you can download .deb [there](https://www.gitkraken.com/download), just select Linux (.deb)
After than you can do [this steps](https://github.com/5cr1pt/GitCracken/issues/34#issuecomment-620003288)

**Comment by damianlluch** [comment]
I installed it with .deb and executed the script with the node. 
When I open the GitKraken in the license section I see that it keeps telling me that the license expires in 7 days.

Is that OK or not?

**Comment by djmemo** [comment]
At the first start it can have this message.  thereafter at the bottom right there will be written 'Pro' to replace 'Free'

**Comment by damianlluch** [comment]
Hello, I open the application several times, and the message is always PRO and when I click, the application shows the remaining days of the license.

I tried execute other time, and I get this result:


amian@damian-Latitude-E5450:~/Downloads/GitCracken/GitCracken$ sudo node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"

 ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
 ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
                                                                               
• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

==> 📦 Backup /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app.asar.1594035738314.backup
==> 🔓 Unpack /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app
==> 🔨 Patch /usr/share/gitkraken/resources/app with pro features
(node:426658) UnhandledPromiseRejectionWarning: Error: Can't patch static/index.js
    at Patcher.patchDirWithPatch (/home/damian/Downloads/GitCracken/GitCracken/dist/src/patcher.js:102:19)
    at Patcher.patchDirWithFeature (/home/damian/Downloads/GitCracken/GitCracken/dist/src/patcher.js:95:18)
    at Patcher.patchDir (/home/damian/Downloads/GitCracken/GitCracken/dist/src/patcher.js:89:18)
    at executeActions (/home/damian/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
    at Command.program.name.description.option.option.option.arguments.action (/home/damian/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/damian/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/home/damian/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/damian/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/damian/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
(node:426658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:426658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AchmadFathoni** [comment]
> Can't patch static/index.js

Try reinstall your Gitkraken

**Comment by AchmadFathoni** [comment]
> Hello, I open the application several times, and the message is always PRO and when I click, the application shows the remaining days of the license.
> 
> I tried execute other time, and I get this result:
> 
> amian@damian-Latitude-E5450:~/Downloads/GitCracken/GitCracken$ sudo node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"
> 
> ██████╗ ██╗████████╗ ██████╗██████╗ █████╗ ██████╗██╗ ██╗███████╗███╗ ██╗
> ██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗ ██║
> ██║ ███╗██║ ██║ ██║ ██████╔╝███████║██║ █████╔╝ █████╗ ██╔██╗ ██║
> ██║ ██║██║ ██║ ██║ ██╔══██╗██╔══██║██║ ██╔═██╗ ██╔══╝ ██║╚██╗██║
> ╚██████╔╝██║ ██║ ╚██████╗██║ ██║██║ ██║╚██████╗██║ ██╗███████╗██║ ╚████║
> ╚═════╝ ╚═╝ ╚═╝ ╚═════╝╚═╝ ╚═╝╚═╝ ╚═╝ ╚═════╝╚═╝ ╚═╝╚══════╝╚═╝ ╚═══╝
> 
> • Description: GitKraken utils for non-commercial use
> • Version: 0.6.2
> • Author: KillWolfVlad
> • License: MIT
> • Home Page: https://pastebin.com/u/KillWolfVlad
> 
> ==> package Backup /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app.asar.1594035738314.backup
> ==> unlock Unpack /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app
> ==> hammer Patch /usr/share/gitkraken/resources/app with pro features
> (node:426658) UnhandledPromiseRejectionWarning: Error: Can't patch static/index.js
> at Patcher.patchDirWithPatch (/home/damian/Downloads/GitCracken/GitCracken/dist/src/patcher.js:102:19)
> at Patcher.patchDirWithFeature (/home/damian/Downloads/GitCracken/GitCracken/dist/src/patcher.js:95:18)
> at Patcher.patchDir (/home/damian/Downloads/GitCracken/GitCracken/dist/src/patcher.js:89:18)
> at executeActions (/home/damian/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
> at Command.program.name.description.option.option.option.arguments.action (/home/damian/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
> at Command.listener (/home/damian/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
> at Command.emit (events.js:198:13)
> at Command.parseArgs (/home/damian/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
> at Command.parse (/home/damian/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
> at Object. (/home/damian/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
> at Module._compile (internal/modules/cjs/loader.js:778:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> (node:426658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:426658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Try reinstall your Gitkraken

**Comment by luyang93** [comment]
> i tried on ubuntu 20.04, with a fresh install of the 6.6 (the last version to date) and it works, it should also work on 18.04, try
> 
> start clean
> 
> ```
> sudo apt-get autoremove gitcraken
> sudo rm -rf /usr/share/gitcraken
> sudo dpkg -i gitcraken-amd64.deb
> ```
> 
> than
> 
> ```
> git clone https://github.com/5cr1pt/GitCracken
> cd GitCracken/GitCracken/
> yarn install
> yarn build
> sudo node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"   
> ```
> 
> if you are using `nvm` or any node version manager, put the entire path to node for me it was
> 
> ```
>  sudo /home/MY_USER_NAME/.nvm/versions/node/v10.18.0/bin/node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"  
> ```

it works on version 7.1.0 on Linux Mint 19.3 Tricia

**Comment by louis2688** [comment]
> i tried on ubuntu 20.04, with a fresh install of the 6.6 (the last version to date) and it works, it should also work on 18.04, try
> 
> start clean
> 
> ```
> sudo apt-get autoremove gitcraken
> sudo rm -rf /usr/share/gitcraken
> sudo dpkg -i gitcraken-amd64.deb
> ```
> 
> than
> 
> ```
> git clone https://github.com/5cr1pt/GitCracken
> cd GitCracken/GitCracken/
> yarn install
> yarn build
> sudo node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"   
> ```
> 
> if you are using `nvm` or any node version manager, put the entire path to node for me it was
> 
> ```
>  sudo /home/MY_USER_NAME/.nvm/versions/node/v10.18.0/bin/node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"  
> ```

this steps works with me, Im using Pop_os 20.04 with stable version of node and npm and latest gitkraken.

**Comment by Icedroid** [comment]
the same error in mac. Who know how to fix it for mac?
