### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Can't patch static/index.js at Patcher.patchDirWithPatch

### ISSUE THREAD

**Issue by Mike-Antipov** [5cr1pt/GitCracken#36]
macOS Mojave, Node 12, GitKraken 6.6.0.

`Patch /Applications/GitKraken.app/Contents/Resources/app with pro features
(node:39582) UnhandledPromiseRejectionWarning: Error: Can't patch static/index.js
    at Patcher.patchDirWithPatch (/Volumes/SEAGATE 500/GitCracken/GitCracken/dist/src/patcher.js:102:19)
    at Patcher.patchDirWithFeature (/Volumes/SEAGATE 500/GitCracken/GitCracken/dist/src/patcher.js:95:18)
    at Patcher.patchDir (/Volumes/SEAGATE 500/GitCracken/GitCracken/dist/src/patcher.js:89:18)
    at executeActions (/Volumes/SEAGATE 500/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
    at Command.<anonymous> (/Volumes/SEAGATE 500/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/Volumes/SEAGATE 500/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/Volumes/SEAGATE 500/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/Volumes/SEAGATE 500/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Volumes/SEAGATE 500/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39582) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:39582) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by yicijohncy** [comment]
have the same situation

**Comment by Mike-Antipov** [comment]
> have the same situation

I don't know what was the cause, but several days after I've reinstalled GitKraken, rebuilt the patcher and everything just worked.

**Comment by AchmadFathoni** [comment]
> > have the same situation
> 
> I don't know what was the cause, but several days after I've reinstalled GitKraken, rebuilt the patcher and everything just worked.

Yeah,  for me reinstall the Gitkraken fix this issue
