### ISSUE TITLE
How Execute?

### ISSUE THREAD

**Issue by damianlluch** [5cr1pt/GitCracken#43]
Hi!, thanks fot a lot.

How execute a GitKraken? I follow the instructions but I not clear how run the app.

thanks.

**Comment by djmemo** [comment]
just install Gitkraken and follow the instructions https://github.com/5cr1pt/GitCracken#quick-start

**Comment by damianlluch** [comment]
Yes... I follow this instructions, but which is the commando for execute app?

**Comment by djmemo** [comment]
GitCraken launches with Yarn on the command line when it is finished you just need to run GitKraken normally as a classic application.

**Comment by damianlluch** [comment]
damian@damian-Latitude-E5450:~/Documents/GitCracken/GitCracken$ node dist/bin/gitcracken.js patcher

 ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
 ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
                                                                               
• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

(node:12356) UnhandledPromiseRejectionWarning: Error: Can't find app.asar!
    at new Patcher (/home/damian/Documents/GitCracken/GitCracken/dist/src/patcher.js:55:19)
    at executeActions (/home/damian/Documents/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:9:21)
    at Command.program.name.description.option.option.option.arguments.action (/home/damian/Documents/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/damian/Documents/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/home/damian/Documents/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/damian/Documents/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/damian/Documents/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:12356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by djmemo** [comment]
Gitkraken is installed ?

**Comment by damianlluch** [comment]
do you have to install gitkraken in addition to following the instructions in this repository?

**Comment by djmemo** [comment]
Yes first you have to install GitKraken then follow the instructions.

**Comment by damianlluch** [comment]
ok.

I have this result:

(node:19315) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/usr/share/gitkraken/resources/app.asar'


any suggestion?

**Comment by djmemo** [comment]
Duplicate of #34

**Comment by martinamunoz** [comment]
I've installed GitKraken, then followed the instructions, and executed the Yarn commands. Finally opened GitKraken from the icon. It works perfectly
