### ISSUE TITLE
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]

### ISSUE THREAD

**Issue by hydr8-code** [5cr1pt/GitCracken#50]
Sup guys,

at first I faced the already solved problem with the asar.js. But the helpful issues helped me to solve this one. 
No iam facing another problem after execution of the following line:

`node dist/bin/gitcracken.js patcher --asar node_modules/asar/bin/asar.js`

And the Error:

`• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

==> 📦 Backup node_modules/asar/bin/asar.js ➔ node_modules/asar/bin/asar.js.1599686311212.backup
==> 🔓 Unpack node_modules/asar/bin/asar.js ➔ node_modules/asar/bin/asar
(node:48874) UnhandledPromiseRejectionWarning: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:79:11)
    at Buffer.readUInt32LE (internal/buffer.js:215:5)
    at Pickle.getPayloadSize (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/chromium-pickle-js/lib/pickle.js:192:24)
    at new PickleIterator (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/chromium-pickle-js/lib/pickle.js:27:28)
    at Pickle.createIterator (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/chromium-pickle-js/lib/pickle.js:144:12)
    at Object.module.exports.readArchiveHeaderSync (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/asar/lib/disk.js:68:23)
    at Object.module.exports.readFilesystemSync (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/asar/lib/disk.js:84:25)
    at Object.module.exports.extractAll (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/asar/lib/asar.js:170:27)
    at Patcher.unpackAsar (/home/b0x/Downloads/GitCracken/GitCracken/dist/src/patcher.js:79:14)
    at executeActions (/home/b0x/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:23:25)
    at Command.<anonymous> (/home/b0x/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:314:20)
    at Command.parseArgs (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/b0x/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:48874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:48874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Node Version v14.9.0

Any suggestions?

Thanks in advance.

**Comment by hydr8-code** [comment]
Update: I found my mistake and replaced the wrong filename:
`node dist/bin/gitcracken.js patcher --asar node_modules/asar/bin/asar.js`
to
`node dist/bin/gitcracken.js patcher --asar node_modules/asar/bin/app.asar`

But now im facing a different Problem, seems that electron is making some serious problemes...

`==> 📦 Backup node_modules/electron/dist/resources/default_app.asar ➔ node_modules/electron/dist/resources/default_app.asar.1599689860700.backup
==> 🔓 Unpack node_modules/electron/dist/resources/default_app.asar ➔ node_modules/electron/dist/resources/default_app
==> 🔨 Patch node_modules/electron/dist/resources/default_app with pro features
fs.js:465
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'node_modules/electron/dist/resources/default_app/static/index.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at Patcher.patchDirWithPatch (/home/b0x/Downloads/GitCracken/GitCracken/dist/src/patcher.js:99:31)
    at Patcher.patchDirWithFeature (/home/b0x/Downloads/GitCracken/GitCracken/dist/src/patcher.js:95:18)
    at Patcher.patchDir (/home/b0x/Downloads/GitCracken/GitCracken/dist/src/patcher.js:89:18)
    at executeActions (/home/b0x/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
    at Command.<anonymous> (/home/b0x/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:314:20)
    at Command.parseArgs (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/b0x/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'node_modules/electron/dist/resources/default_app/static/index.js'
}
`

**Comment by rickyrickc137** [comment]
> Update: I found my mistake and replaced the wrong filename:
> `node dist/bin/gitcracken.js patcher --asar node_modules/asar/bin/asar.js`
> to
> `node dist/bin/gitcracken.js patcher --asar node_modules/asar/bin/app.asar`
> 
> But now im facing a different Problem, seems that electron is making some serious problemes...
> 
> ```
> ==> 📦 Backup node_modules/electron/dist/resources/default_app.asar ➔ node_modules/electron/dist/resources/default_app.asar.1599689860700.backup
> ==> 🔓 Unpack node_modules/electron/dist/resources/default_app.asar ➔ node_modules/electron/dist/resources/default_app
> ==> 🔨 Patch node_modules/electron/dist/resources/default_app with pro features
> fs.js:465
>   handleErrorFromBinding(ctx);
>   ^
> 
> Error: ENOENT: no such file or directory, open 'node_modules/electron/dist/resources/default_app/static/index.js'
>     at Object.openSync (fs.js:465:3)
>     at Object.readFileSync (fs.js:368:35)
>     at Patcher.patchDirWithPatch (/home/b0x/Downloads/GitCracken/GitCracken/dist/src/patcher.js:99:31)
>     at Patcher.patchDirWithFeature (/home/b0x/Downloads/GitCracken/GitCracken/dist/src/patcher.js:95:18)
>     at Patcher.patchDir (/home/b0x/Downloads/GitCracken/GitCracken/dist/src/patcher.js:89:18)
>     at executeActions (/home/b0x/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
>     at Command.<anonymous> (/home/b0x/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
>     at Command.listener (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
>     at Command.emit (events.js:314:20)
>     at Command.parseArgs (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
>     at Command.parse (/home/b0x/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
>     at Object.<anonymous> (/home/b0x/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
>     at Module._compile (internal/modules/cjs/loader.js:1075:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
>     at Module.load (internal/modules/cjs/loader.js:940:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:781:14) {
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: 'node_modules/electron/dist/resources/default_app/static/index.js'
> }
> ```

Did you solve the problem?
