### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, copyfile '/usr/share/gitkraken/resources/app.asar' -> '/usr/share/gitkraken/resources/app.asar.1600202936544.backup'

### ISSUE THREAD

**Issue by joaquiponce44** [5cr1pt/GitCracken#51]
Hi I just finished following the installation steps and when I run the last command I get this error, any quick solution? thank you

 ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
 ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
                                                                               
• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

(node:10966) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, copyfile '/usr/share/gitkraken/resources/app.asar' -> '/usr/share/gitkraken/resources/app.asar.1600202936544.backup'
    at Object.copyFileSync (fs.js:1728:3)
    at copyFile (/home/joaquin/GitCracken/GitCracken/node_modules/fs-extra/lib/copy-sync/copy-sync.js:68:8)
    at onFile (/home/joaquin/GitCracken/GitCracken/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
    at getStats (/home/joaquin/GitCracken/GitCracken/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/home/joaquin/GitCracken/GitCracken/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/home/joaquin/GitCracken/GitCracken/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/home/joaquin/GitCracken/GitCracken/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at Patcher.backupAsar (/home/joaquin/GitCracken/GitCracken/dist/src/patcher.js:75:12)
    at executeActions (/home/joaquin/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:18:95)
    at Command.program.name.description.option.option.option.arguments.action (/home/joaquin/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/joaquin/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/home/joaquin/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/joaquin/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/joaquin/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
(node:10966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10966) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hydr8-code** [comment]
Did you tried it as a sudo user? Permission denied in Linux is almost every time a prvilege problem. Try to run the patcher with sudo.

**Comment by ilhammalik113** [comment]
please update nodejs version the lates

**Comment by toanbku** [comment]
You can change permission of this folder, then run again.
```
sudo chmod -R 777 /usr/share/gitkraken/resources
```

**Comment by bawantha** [comment]
`sudo node dist/bin/gitcracken.js patcher` works
