### ISSUE TITLE
app.asar error ?

### ISSUE THREAD

**Issue by JuanFrAguirre** [5cr1pt/GitCracken#52]
Hi, I can't finish my installation process due to the following error.
I tried doing it in both Ubuntu 18.4 and 20.4, as a sudo user, etc.
I wonder if this is a bug that has yet to be fixed?

 ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
 ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
                                                                               
• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

(node:22303) UnhandledPromiseRejectionWarning: Error: Can't find app.asar!
    at new Patcher (/home/juan/GitCracken/GitCracken/dist/src/patcher.js:55:19)
    at executeActions (/home/juan/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:9:21)
    at Command.program.name.description.option.option.option.arguments.action (/home/juan/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/juan/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/home/juan/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/juan/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/juan/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:22303) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22303) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ilhammalik113** [comment]
please update nodejs version the lates

**Comment by HuangYog** [comment]
不要直接在应用商店中的安装，去官网下载安装包安装
Do not install directly in the app store, go to the official website to download the installation package

**Comment by aghayeff** [comment]
> 不要直接在应用商店中的安装，去官网下载安装包安装
> Do not install directly in the app store, go to the official website to download the installation package

You mean installing GitKraken?
