### ISSUE TITLE
Crack 7.4.0 failed

### ISSUE THREAD

**Issue by rj-hwang** [5cr1pt/GitCracken#55]
Platform: Windows-10-64Bit

```
$ node dist/bin/gitcracken.js patcher

 ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
 ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝

• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

==> � Backup C:\Users\gftaxi\AppData\Local\gitkraken\app-7.4.0\resources\app.asar ➔ C:\Users\gftaxi\AppData\Local\gitkraken\app-7.4.0\
resources\app.asar.1603956815428.backup
==> � Unpack C:\Users\gftaxi\AppData\Local\gitkraken\app-7.4.0\resources\app.asar ➔ C:\Users\gftaxi\AppData\Local\gitkraken\app-7.4.0\
resources\app
==> � Patch C:\Users\gftaxi\AppData\Local\gitkraken\app-7.4.0\resources\app with pro features
(node:5812) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\gftaxi\AppData\Local\gitkraken\a
pp-7.4.0\resources\app\static\index.js'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Patcher.patchDirWithPatch (D:\open-source\GitCracken\GitCracken\dist\src\patcher.js:99:31)
    at Patcher.patchDirWithFeature (D:\open-source\GitCracken\GitCracken\dist\src\patcher.js:95:18)
    at Patcher.patchDir (D:\open-source\GitCracken\GitCracken\dist\src\patcher.js:89:18)
    at executeActions (D:\open-source\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:31:25)
    at Command.program.name.description.option.option.option.arguments.action (D:\open-source\GitCracken\GitCracken\dist\bin\gitcracken
-patcher.js:87:11)
    at Command.listener (D:\open-source\GitCracken\GitCracken\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (D:\open-source\GitCracken\GitCracken\node_modules\commander\index.js:665:12)
    at Command.parse (D:\open-source\GitCracken\GitCracken\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (D:\open-source\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
(node:5812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not h
andled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Kortivex** [comment]
Same in Manjaro Linux 5.9.1

**Comment by theupriser** [comment]
Location of index.js changed to:
C:\Users\{{ USER }}\AppData\Local\gitkraken\app-7.4.0\resources\app\src\render\static\entryPoints\main\

**Comment by Charis1331** [comment]
> Location of index.js changed to:
> C:\Users{{ USER }}\AppData\Local\gitkraken\app-7.4.0\resources\app\src\render\static\entryPoints\main\

Any idea where this folder is referenced in the code? I can't seem to find it.

**Comment by dj-nitehawk** [comment]
https://github.com/5cr1pt/GitCracken/pull/54
the PR works. 
wait till it gets merged to master or do it locally if impatient.

**Comment by theupriser** [comment]
> > Location of index.js changed to:
> > C:\Users{{ USER }}\AppData\Local\gitkraken\app-7.4.0\resources\app\src\render\static\entryPoints\main\
> 
> Any idea where this folder is referenced in the code? I can't seem to find it.

I've searched for it, couldn't find it.

> #54
> the PR works.
> wait till it gets merged to master or do it locally if impatient.

What do you mean by PR?

**Comment by loudywen** [comment]
very nice.. the pr worked. thx

**Comment by rj-hwang** [comment]
PR #54 worked.

**Comment by HuangYog** [comment]
linux 上建议切换到root用户后执行最后的这步“node dist/bin/gitcracken.js patcher”
亲试有效！！！已上车

**Comment by Winexcel** [comment]
Does it work with the latest version of 7.5.2?

**Comment by Kortivex** [comment]
Yes, it works, my setup:
- **Manjaro Linux**: v5.11.2
- **Node**: v15.10.0
- **Yarn**: v1.22.10

**Comment by Icedroid** [comment]
Does it work for mac?

**Comment by muhammadZaahid** [comment]
do you have gitkraken version 7.4.0
