### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error

### ISSUE THREAD

**Issue by bernatdelgado87** [5cr1pt/GitCracken#59]
C:\gitcracken\GitCracken>node dist/bin/gitcracken.js patcher

 ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
 ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝

• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

(node:12220) UnhandledPromiseRejectionWarning: Error: Can't find app.asar!
    at new Patcher (C:\gitcracken\GitCracken\dist\src\patcher.js:55:19)
    at executeActions (C:\gitcracken\GitCracken\dist\bin\gitcracken-patcher.js:9:21)
    at Command.<anonymous> (C:\gitcracken\GitCracken\dist\bin\gitcracken-patcher.js:87:11)
    at Command.listener (C:\gitcracken\GitCracken\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (C:\gitcracken\GitCracken\node_modules\commander\index.js:665:12)
    at Command.parse (C:\gitcracken\GitCracken\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\gitcracken\GitCracken\dist\bin\gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:12220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JTangming** [comment]
+1

**Comment by Husseinhj** [comment]
+1

**Comment by penetratorGithub** [comment]
try 
1.  delete gitkraken installation directories  (3 directories)
2.  delete this repository and clone again
3.  node 12+   `node -v`     and   yarn   1.22+   `yarn -v`
4. install gitkraken and start session
5. add domain to host
6. follow readme.md
7. enjoy


if fails....
follow steps

**Comment by bernatdelgado87** [comment]
working
thank you

**Comment by dmcshehan** [comment]
Thank you
