### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hadenix** [5cr1pt/GitCracken#60]
`hadenix@hadenix-desktop:~/Загрузки/GitCracken/GitCracken$ node dist/bin/gitcracken.js patcher

 ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
 ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
                                                                               
• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

(node:5262) UnhandledPromiseRejectionWarning: Error: Can't find app.asar!
    at new Patcher (/home/hadenix/Загрузки/GitCracken/GitCracken/dist/src/patcher.js:55:19)
    at executeActions (/home/hadenix/Загрузки/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:9:21)
    at Command.program.name.description.option.option.option.arguments.action (/home/hadenix/Загрузки/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/hadenix/Загрузки/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/home/hadenix/Загрузки/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/hadenix/Загрузки/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/hadenix/Загрузки/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:5262) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5262) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by penetratorGithub** [comment]
try 
1.  delete gitkraken installation directories  (3 directories)
2.  delete this repository and clone again
3.  node 12+   `node -v`     and   yarn   1.22+   `yarn -v`
4. install gitkraken and start session
5. add domain to host
6. follow readme.md
7. enjoy


if fails....
follow steps
