### ISSUE TITLE
Can not patch 

### ISSUE THREAD

**Issue by simonjhy** [5cr1pt/GitCracken#61]
==> 📦 Backup /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app.asar.1606096703861.backup
==> 🔓 Unpack /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app
==> 🔨 Patch /usr/share/gitkraken/resources/app with pro features
(node:7488) UnhandledPromiseRejectionWarning: Error: Can't patch src/render/static/entryPoints/main/index.js
    at Patcher.patchDirWithPatch (/home/simon/work/github/GitCracken/GitCracken/dist/src/patcher.js:102:19)
    at Patcher.patchDirWithFeature (/home/simon/work/github/GitCracken/GitCracken/dist/src/patcher.js:95:18)
    at Patcher.patchDir (/home/simon/work/github/GitCracken/GitCracken/dist/src/patcher.js:89:18)
    at executeActions (/home/simon/work/github/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
    at Command.<anonymous> (/home/simon/work/github/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/simon/work/github/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/home/simon/work/github/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/simon/work/github/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/simon/work/github/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by mustafa-barakat** [comment]
what's your version of the application ?

**Comment by MaBbKhawaja** [comment]
same error

**Comment by gabernardi** [comment]
anyone?

**Comment by douzsh** [comment]
same probleam

**Comment by luxam** [comment]
同样的问题

**Comment by IZanith** [comment]
same error!!!!!!who can help me?

**Comment by IZanith** [comment]
==> � Backup C:/Users/user/AppData/Local/gitkraken/app-6.5.0/resources/app.as
ar ➔ C:/Users/user/AppData/Local/gitkraken/app-6.5.0/resources/app.asar.161219
0707705.backup
==> � Unpack C:/Users/user/AppData/Local/gitkraken/app-6.5.0/resources/app.as
ar ➔ C:\Users\user\AppData\Local\gitkraken\app-6.5.0\resources\app
==> � Patch C:\Users\user\AppData\Local\gitkraken\app-6.5.0\resources\app wit
h pro features
(node:6112) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or dir
ectory, open 'C:\Users\user\AppData\Local\gitkraken\app-6.5.0\resources\app\sr
c\render\static\entryPoints\main\index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Patcher.patchDirWithPatch (C:\Users\user\GitCracken\GitCracken\dist\src
\patcher.js:100:31)
    at Patcher.patchDirWithFeature (C:\Users\user\GitCracken\GitCracken\dist\s
rc\patcher.js:96:18)
    at Patcher.patchDir (C:\Users\user\GitCracken\GitCracken\dist\src\patcher.
js:90:18)
    at executeActions (C:\Users\user\GitCracken\GitCracken\dist\bin\gitcracken
-patcher.js:31:25)
    at Command.<anonymous> (C:\Users\user\GitCracken\GitCracken\dist\bin\gitcr
acken-patcher.js:87:11)
    at Command.listener (C:\Users\user\GitCracken\GitCracken\node_modules\comm
ander\index.js:315:8)
    at Command.emit (events.js:314:20)
    at Command.parseArgs (C:\Users\user\GitCracken\GitCracken\node_modules\com
mander\index.js:665:12)
    at Command.parse (C:\Users\user\GitCracken\GitCracken\node_modules\command
er\index.js:474:21)
    at Object.<anonymous> (C:\Users\user\GitCracken\GitCracken\dist\bin\gitcra
cken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
(node:6112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 2)
(node:6112) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by ShanQincheng** [comment]
Gitkraken version: 7.5.5
Windows 10

SOLUTION:
1、Reinstall Gitkraken
2、Rerun 5cr1pt/GitCracken Home Page **Quick start**
3、Done

**Comment by juanantoniodamianv** [comment]
anyone?
