### ISSUE TITLE
Not working with 7.4.1

### ISSUE THREAD

**Issue by mustafa-barakat** [5cr1pt/GitCracken#62]
==> 📦 Backup C:\Users\MyUSERNAME\AppData\Local\gitkraken\app-7.4.1\resources\app.asar ➔ C:\Users\MyUSERNAME\AppData\Local\gitkraken\app-7.4.1\resources\app.asar.1606893893805.backup
==> 🔓 Unpack C:\Users\MyUSERNAME\AppData\Local\gitkraken\app-7.4.1\resources\app.asar ➔ C:\Users\MyUSERNAME\AppData\Local\gitkraken\app-7.4.1\resources\app
==> 🔨 Patch C:\Users\MyUSERNAME\AppData\Local\gitkraken\app-7.4.1\resources\app with pro features
(node:26592) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\MyUSERNAME\AppData\Local\gitkraken\app-7.4.1\resources\app\static\index.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Patcher.patchDirWithPatch (C:\Users\MyUSERNAME\Documents\GitCracken\GitCracken\dist\src\patcher.js:99:31)
    at Patcher.patchDirWithFeature (C:\Users\MyUSERNAME\Documents\GitCracken\GitCracken\dist\src\patcher.js:95:18)
    at Patcher.patchDir (C:\Users\MyUSERNAME\Documents\GitCracken\GitCracken\dist\src\patcher.js:89:18)
    at executeActions (C:\Users\MyUSERNAME\Documents\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:31:25)
    at Command.<anonymous> (C:\Users\MyUSERNAME\Documents\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:87:11)
    at Command.listener (C:\Users\MyUSERNAME\Documents\GitCracken\GitCracken\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (C:\Users\MyUSERNAME\Documents\GitCracken\GitCracken\node_modules\commander\index.js:665:12)
    at Command.parse (C:\Users\MyUSERNAME\Documents\GitCracken\GitCracken\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\MyUSERNAME\Documents\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mustafa-barakat** [comment]
Fixed, was using old version of repo
