### ISSUE TITLE
An error occurred while trying to execute the follow command

### ISSUE THREAD

**Issue by dimplememory** [5cr1pt/GitCracken#69]
localhost:GitCracken Phoenix$ node dist/bin/gitcracken.js patcher
/Users/xxx/Desktop/Project/GitCracken/GitCracken/dist/src/appId.js:24
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/Desktop/Project/GitCracken/GitCracken/dist/src/index.js:13:14)

**Comment by guimurgel** [comment]
Duplicate of #57
