### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by astrot1988** [5cr1pt/GitCracken#7]
PS D:\GitCracken-master\GitCracken> node dist/bin/gitcracken.js patcher
D:\GitCracken-master\GitCracken\dist\src\appId.js:23
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\GitCracken-master\GitCracken\dist\src\index.js:6:10)

**Comment by oliva1337** [comment]
fuck

**Comment by arklid** [comment]
Make sure you have Node.js v10 LTS or later installed in your Windows environment. It should solve the issue you are having.

**Comment by Luc45** [comment]
I'm having the same issue. node v10.15.0 (npm v6.4.1). Ubuntu 18.04 LTS.

```
➜ GitCracken sudo node dist/bin/gitcracken.js about  
/home/lucas/programs/gitkraken-crack/GitCracken/dist/src/appId.js:23
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lucas/programs/gitkraken-crack/GitCracken/dist/src/index.js:6:10)
```

**Comment by Luc45** [comment]
Got it! Ran:

1. `sudo chown -R lucas:lucas /usr/share/gitkraken/resources`
2. `node dist/bin/gitcracken.js patcher` (without sudo)

Worked flawlessly.

Thanks a lot!
