### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Can't find app.asar!

### ISSUE THREAD

**Issue by ShipmasterKyle** [5cr1pt/GitCracken#70]
(node:31251) UnhandledPromiseRejectionWarning: Error: Can't find app.asar!
    at new Patcher (/home/kyle/GitCracken/GitCracken/dist/src/patcher.js:55:19)
    at executeActions (/home/kyle/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:9:21)
    at Command.<anonymous> (/home/kyle/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/kyle/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:314:20)
    at Command.parseArgs (/home/kyle/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/kyle/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/kyle/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
(node:31251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:31251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Powersel** [comment]
Same issue

**Comment by Powersel** [comment]
PS. Have resolved it. Version from popOS internal app store, gave me same error. Removed it (uninstall), loaded deb package for Linux (official Kraken page), installed it, script have worked properly now.
