### ISSUE TITLE
Mac Mini M1 Crack v 7.6.1 : UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by bawa-ra** [5cr1pt/GitCracken#82]
```
(node:1639) UnhandledPromiseRejectionWarning: Error: Can't patch src/render/static/entryPoints/main/index.js
    at Patcher.patchDirWithPatch (/Users/bawa/Downloads/GitCracken-master/GitCracken/dist/src/patcher.js:102:19)
    at Patcher.patchDirWithFeature (/Users/bawa/Downloads/GitCracken-master/GitCracken/dist/src/patcher.js:95:18)
    at Patcher.patchDir (/Users/bawa/Downloads/GitCracken-master/GitCracken/dist/src/patcher.js:89:18)
    at executeActions (/Users/bawa/Downloads/GitCracken-master/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
    at Command.<anonymous> (/Users/bawa/Downloads/GitCracken-master/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/Users/bawa/Downloads/GitCracken-master/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:376:20)
    at Command.parseArgs (/Users/bawa/Downloads/GitCracken-master/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/Users/bawa/Downloads/GitCracken-master/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/bawa/Downloads/GitCracken-master/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1639) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by bawa-ra** [comment]
#79  
This works
