### ISSUE TITLE
Not working with GitKracken 5.0.4, NPM 6.14.4 and Node 12.16.2 on Mac OS X 10.13.6

### ISSUE THREAD

**Issue by OMA2k** [5cr1pt/GitCracken#83]
I followed the instructions. Since Yarn was required, I installed it with:

sudo npm install --global yarn

Then I typed all the required commands:

git clone https://github.com/5cr1pt/GitCracken.git
cd GitCracken/GitCracken/
yarn install
yarn build
node dist/bin/gitcracken.js patcher

The last command (the patcher call) showed the following:

GITCRACKEN
                                                                               
• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

==> 📦 Backup /Applications/GitKraken.app/Contents/Resources/app.asar ➔ /Applications/GitKraken.app/Contents/Resources/app.asar.1623452611856.backup
==> 🔓 Unpack /Applications/GitKraken.app/Contents/Resources/app.asar ➔ /Applications/GitKraken.app/Contents/Resources/app
==> 🔨 Patch /Applications/GitKraken.app/Contents/Resources/app with pro features
(node:64981) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Applications/GitKraken.app/Contents/Resources/app/src/render/static/entryPoints/main/index.js'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Patcher.patchDirWithPatch (/Volumes/DATA/Software/GitKraken/GitCracken/GitCracken/dist/src/patcher.js:99:31)
    at Patcher.patchDirWithFeature (/Volumes/DATA/Software/GitKraken/GitCracken/GitCracken/dist/src/patcher.js:95:18)
    at Patcher.patchDir (/Volumes/DATA/Software/GitKraken/GitCracken/GitCracken/dist/src/patcher.js:89:18)
    at executeActions (/Volumes/DATA/Software/GitKraken/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
    at Command.<anonymous> (/Volumes/DATA/Software/GitKraken/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/Volumes/DATA/Software/GitKraken/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:310:20)
    at Command.parseArgs (/Volumes/DATA/Software/GitKraken/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/Volumes/DATA/Software/GitKraken/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Volumes/DATA/Software/GitKraken/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
(node:64981) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:64981) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Is this an actual bug or am I doing something wrong?

**Comment by Icedroid** [comment]
GitKracken 7 also seen the same error

**Comment by huylv-teko** [comment]
same error

**Comment by mreguly** [comment]
same error

**Comment by MaBbKhawaja** [comment]
> patcher is working with version 7.5.5

can you provide version 7.5.5 .deb file ???

**Comment by onlycalm** [comment]
I tried to crack v7.5.5, but he still showed FREE
