### ISSUE TITLE
Getting an error message for node on last command 

### ISSUE THREAD

**Issue by Shehryar169** [5cr1pt/GitCracken#86]
(node:18761) UnhandledPromiseRejectionWarning: Error: Can't find app.asar!
    at new Patcher (/home/shehryar/Downloads/GitCracken/GitCracken/dist/src/patcher.js:55:19)
    at executeActions (/home/shehryar/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:9:21)
    at Command.<anonymous> (/home/shehryar/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/shehryar/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:400:28)
    at Command.parseArgs (/home/shehryar/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/shehryar/Downloads/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/shehryar/Downloads/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18761) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by PMExtra** [comment]
The official release only support until GitKraken v7.6.1.
Please try #79 for v7.7.0 and later.
