### ISSUE TITLE
not handled will terminate the Node.js process with a non-zero exit code.

### ISSUE THREAD

**Issue by MaBbKhawaja** [5cr1pt/GitCracken#87]
sudo node dist/bin/gitcracken.js patcher --asar "/usr/share/gitkraken/resources/app.asar"

 ██████╗ ██╗████████╗ ██████╗██████╗  █████╗  ██████╗██╗  ██╗███████╗███╗   ██╗
██╔════╝ ██║╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██╔════╝████╗  ██║
██║  ███╗██║   ██║   ██║     ██████╔╝███████║██║     █████╔╝ █████╗  ██╔██╗ ██║
██║   ██║██║   ██║   ██║     ██╔══██╗██╔══██║██║     ██╔═██╗ ██╔══╝  ██║╚██╗██║
╚██████╔╝██║   ██║   ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║ ╚████║
 ╚═════╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝
                                                                               
• Description: GitKraken utils for non-commercial use
• Version: 0.6.2
• Author: KillWolfVlad
• License: MIT
• Home Page: https://pastebin.com/u/KillWolfVlad

==> 📦 Backup /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app.asar.1629580169986.backup
==> 🔓 Unpack /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app
==> 🔨 Patch /usr/share/gitkraken/resources/app with pro features
(node:123079) UnhandledPromiseRejectionWarning: Error: Can't patch src/render/static/entryPoints/main/index.js
    at Patcher.patchDirWithPatch (/home/mabbkhawaja/projects/GitCracken/GitCracken/dist/src/patcher.js:103:19)
    at Patcher.patchDirWithFeature (/home/mabbkhawaja/projects/GitCracken/GitCracken/dist/src/patcher.js:96:18)
    at Patcher.patchDir (/home/mabbkhawaja/projects/GitCracken/GitCracken/dist/src/patcher.js:90:18)
    at executeActions (/home/mabbkhawaja/projects/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
    at Command.<anonymous> (/home/mabbkhawaja/projects/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/mabbkhawaja/projects/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:400:28)
    at Command.parseArgs (/home/mabbkhawaja/projects/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/mabbkhawaja/projects/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/mabbkhawaja/projects/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:123079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:123079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MaBbKhawaja** [comment]
Solved this issue by checkout PR#79
