### ISSUE TITLE
 UnhandledPromiseRejectionWarning: 

### ISSUE THREAD

**Issue by kynightyk** [5cr1pt/GitCracken#90]
when I use 8.0.0 version ,i was In trouble with
==> � Backup C:\Users\123\AppData\Local\gitkraken\app-8.0.0\resources\app.asar ➔ C:\Users\123\AppData\Local\gitkraken\app-8.0.0\resources\app.asar.16330129819
97.backup
==> � Unpack C:\Users\123\AppData\Local\gitkraken\app-8.0.0\resources\app.asar ➔ C:\Users\123\AppData\Local\gitkraken\app-8.0.0\resources\app
==> � Patch C:\Users\123\AppData\Local\gitkraken\app-8.0.0\resources\app with pro features
(node:25280) UnhandledPromiseRejectionWarning: Error: Can't patch src/render/static/entryPoints/main/index.js
    at Patcher.patchDirWithPatch (F:\opensourceInternet\GitCracken\GitCracken\dist\src\patcher.js:102:19)
    at Patcher.patchDirWithFeature (F:\opensourceInternet\GitCracken\GitCracken\dist\src\patcher.js:95:18)
    at Patcher.patchDir (F:\opensourceInternet\GitCracken\GitCracken\dist\src\patcher.js:89:18)
    at executeActions (F:\opensourceInternet\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:31:25)
    at Command.<anonymous> (F:\opensourceInternet\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:87:11)
    at Command.listener (F:\opensourceInternet\GitCracken\GitCracken\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (F:\opensourceInternet\GitCracken\GitCracken\node_modules\commander\index.js:665:12)
    at Command.parse (F:\opensourceInternet\GitCracken\GitCracken\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (F:\opensourceInternet\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:89:6)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:25280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catc
h block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhan
dled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate t
he Node.js process with a non-zero exit code.
![image](https://user-images.githubusercontent.com/50066608/135481865-aee3f91c-b93a-4a2d-bbbf-48a0a2521b48.png)

**Comment by flatl** [comment]
Works fine for 7.4.0 version. Here you can download required version `https://release.axocdn.com/linux/GitKraken-v7.4.0.deb`. But don't forget to remove gitkraken and all gitkraken files first, for linux `/usr/share/gitkraken` and `~/.gitkraken`

**Comment by PMExtra** [comment]
Please try #79 for v7.7.0 and later.
