### ISSUE TITLE
Patch for 8.2.2

### ISSUE THREAD

**Issue by insilications** [5cr1pt/GitCracken#93]
Replace your current pro.diff (GitCracken/patches/pro.diff) from https://github.com/PMExtra/GitCracken with this one:

https://github.com/insilications/GitCracken/blob/master/GitCracken/patches/pro.diff

Or simply use my fork: https://github.com/insilications/GitCracken

**Comment by rtx2014** [comment]
8.2.2?
When I use fork, everything is fine, but free.
When I use replacements, it crashes at the last stage with an error.

**Comment by JourneyOver** [comment]
Yea having same issue as rtx, your patch doesn't seem to work at all sadly as it just continues to say free and none of the "pro" features are active. I even tried the methods of refreshing the account and all that to see if it would work and sadly it didn't. Guess best thing for now is just to stick to 8.1.1 and hope for the best that something will come along soon enough that will work on 8.2.0+

**Comment by fabiovac** [comment]
Getting this error, why?

```
/Users/fabio/Desktop/GitCracken/GitCracken/dist/src/patcher.js:102
            throw new Error(`Can't patch ${patch.oldFileName}`);
                  ^

Error: Can't patch src/render/static/entryPoints/main/index.js
    at Patcher.patchDirWithPatch (/Users/fabio/Desktop/GitCracken/GitCracken/dist/src/patcher.js:102:19)
    at Patcher.patchDirWithFeature (/Users/fabio/Desktop/GitCracken/GitCracken/dist/src/patcher.js:95:18)
    at Patcher.patchDir (/Users/fabio/Desktop/GitCracken/GitCracken/dist/src/patcher.js:89:18)
    at executeActions (/Users/fabio/Desktop/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
    at Command.<anonymous> (/Users/fabio/Desktop/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/Users/fabio/Desktop/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:390:28)
    at Command.parseArgs (/Users/fabio/Desktop/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/Users/fabio/Desktop/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/fabio/Desktop/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.2.0
```

Another question. Before running the patcher should I login into my GitKraken account or should I only open the program and then quit it. And the update of the hosts file should be made after the patcher?

Thanks

**Comment by HanFox** [comment]
https://github.com/PMExtra/GitCracken is working with 8.2.0

**Comment by rtx2014** [comment]
> https://github.com/PMExtra/GitCracken is working with 8.2.0

Acknowledged!
